### ISSUE TITLE
Database structure

### ISSUE THREAD

**Issue by pasca-l** [pasca-l/household-app#1]
Database structure for spendings:
```yaml
/spendings:
  /{spendings_id}:
    owner   : string
    editors : array[string]
    (viewer     : string)
    (categories : array[string])
    ...
    /receipts:
      /{receipt_id}:
        created_at    : Timestamp
        updated_at    : Timestamp
        category      : string
        value         : number
        purchase_date : Timestamp
        ...
```

Database structure for vaults (password manager):
```yaml
/vaults:
  /{vault_id}:
    owner   : string
    editors : array[string]
    (viewer : string)
    ...
    /notes:
      /{note_id}:
        created_at : Timestamp
        updated_at : Timestamp
        label      : string
        url        : string
        username   : string
        password   : string
        other      : array[map]
          label   : string
          content : string
        ...
```
